# Generated by Django 5.2 on 2025-04-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='Qfive',
            field=models.CharField(choices=[('A', 'Up to 10'), ('B', 'Up to 50'), ('C', 'Up to 100'), ('D', 'Up to 1,000'), ('E', 'Up to 10,000'), ('F', 'Up to 100,000'), ('G', 'Up to 1,000,000'), ('H', 'More than 1,000,000')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qfour',
            field=models.CharField(choices=[('A', 'Not sure how often the process would need to run'), ('B', 'Once off process (ad hoc remediation)'), ('C', 'Once daily'), ('D', 'Once weekly'), ('E', 'Once monthly'), ('F', 'Once quarterly'), ('G', 'Once annually'), ('H', 'Multiple times daily'), ('I', 'Multiple times weekly'), ('J', 'Multiple times monthly'), ('K', 'Multiple times quarterly')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qsix',
            field=models.CharField(choices=[('A', 'Not sure how much time is required per cycle'), ('B', 'Less than 30 mins per cycle'), ('C', '30-60mins per cycle'), ('D', '60-90mins per cycle'), ('E', '90-120mins per cycle'), ('F', '120-180mins per cycle'), ('G', '180-360mins per cycle'), ('H', '360-520mins per cycle'), ('I', '520-900min per cycle'), ('J', 'More than 900mins per cycle')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qthree',
            field=models.CharField(choices=[('A', 'No human intervention in process'), ('B', 'Single person performing task'), ('C', 'Few people performing same task'), ('D', 'Many people performing same task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='Qone',
            field=models.CharField(choices=[('A', 'Have not estimated the repetitions'), ('B', 'Very little repetitive tasks required'), ('C', 'Some repetitive tasks required'), ('D', 'Many repetitive tasks required'), ('E', 'Extensive repetitive tasks required')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='Qtwo',
            field=models.CharField(choices=[('A', 'Not sure of the status or health of the process'), ('B', 'Some of the process is currently executed in business'), ('C', 'New process is required altogether'), ('D', 'Enhancement to existing process is required'), ('E', 'Entire process is currently executed in business')], max_length=64, null=True),
        ),
    ]
