# Generated by Django 5.2 on 2025-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0002_answers_qfive_answers_qfour_answers_qsix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='Qeight',
            field=models.CharField(choices=[('A', 'Not sure if there are exceptions'), ('B', 'No exceptions'), ('C', 'Alternate workflow managed via systems'), ('D', 'Alternate workflow managed by humans'), ('E', 'Process generates error and fails'), ('F', 'Process terminates ')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qeighteen',
            field=models.CharField(choices=[('A', 'Not sure what environments we have in place'), ('B', 'No, need to be secured'), ('C', 'Yes, but not adequate'), ('D', 'Yes, have DEV, QA and Prod environments'), ('E', 'Yes, have DEV, QA, Pre-Prod and Prod environments')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qeleven',
            field=models.CharField(choices=[('A', 'Yes, other verifiable sources'), ('B', 'Yes, combination of sources and feed types'), ('C', 'Yes, external data from website'), ('D', 'Yes, external information via data feed or file'), ('E', 'Yes, external data from web subscription service'), ('F', 'No external data used / required')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qfifteen',
            field=models.CharField(choices=[('A', 'None at present'), ('B', 'Yes, but not in the next 2 years'), ('C', 'Yes, but not in the next 1 year'), ('D', 'Yes, but not in the next 6 months'), ('E', 'Yes, but not in the next 3 months'), ('F', 'Yes, within next 30 days'), ('G', 'Yes, busy with change right now'), ('H', 'Not sure, need to investigate')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qfourteen',
            field=models.CharField(choices=[('A', 'Not sure what options are available'), ('B', 'No other options considered'), ('C', 'Investigated options but too expensive'), ('D', 'Investigated options but not suited'), ('E', 'Investigated but no other options identified'), ('F', 'Options available but not viable'), ('G', 'Options available but would not meet requirement'), ('H', 'Options are not desirable due to impact on business or customer')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qnine',
            field=models.CharField(choices=[('A', 'Not sure if data is required'), ('B', 'Manual input data'), ('C', 'Unstructured data (eg email / word documents)'), ('D', 'Structured data sources (data file / spread sheet)'), ('E', 'Combination of sources')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qnineteen',
            field=models.CharField(choices=[('A', 'Not sure whether data is representative or available'), ('B', 'Data not available at present'), ('C', 'Although data not available. It can be obtained'), ('D', 'Although data available, it is not entirely suited or aligned'), ('E', 'Accurate data available for some systems but not representative'), ('F', 'Accurate data available for all systems but not representative'), ('G', 'Accurate and representative data available for some systems'), ('H', 'Accurate and representative data available for all systems')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qseven',
            field=models.CharField(choices=[('A', 'No human decisions required'), ('B', 'Simple rule or parameter based decisions'), ('C', 'Complex rule or parameter based decisions'), ('D', 'Decisions require judgement calls not based on parameters'), ('E', 'Not sure, need to investigate')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qseventeen',
            field=models.CharField(choices=[('A', 'Not able to support initiative'), ('B', 'Not sure what is required to support initiative'), ('C', 'Yes, but only limited time available'), ('D', 'Yes, but require additional resources'), ('E', 'Yes, but require additional skills'), ('F', 'Yes, key resources will be allocated to the initiative')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qsixteen',
            field=models.CharField(choices=[('A', 'Not sure if threats are identified or known'), ('B', 'No known threats are this time'), ('C', 'Threat suspected but not confirmed'), ('D', 'Customer impact threat identified'), ('E', 'Key mand dependency identified'), ('F', 'Regulatory compliance threat identified'), ('G', 'Information security / risk threat identified')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qten',
            field=models.CharField(choices=[('A', 'All sources are maintained by IM'), ('B', 'Some of the sources are maintained by IM'), ('C', 'None of the sources are maintained by IM'), ('D', 'Not sure, need to investigate')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qthirteen',
            field=models.CharField(choices=[('A', 'Input data not yet identified'), ('B', 'Some input data is identified '), ('C', 'Most input data is identified'), ('D', 'All input data is identified'), ('E', 'Most input data is identified and available'), ('F', 'All input data is identified and available')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qtwelve',
            field=models.CharField(choices=[('A', 'No own investigation has taken place on contract / legal compliance'), ('B', 'Risk group has identified compliance issues to be resolved'), ('C', 'Risk group have not been engaged to review requirements'), ('D', 'Risk group in process of investigating compliance requirements'), ('E', 'Risk group has validated legal compliance requirements'), ('F', 'Risk group have signed off on all compliance requirements'), ('G', 'No exposure to 3rd party information risk')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qtwenty',
            field=models.CharField(choices=[('A', 'Executive override obtained - proceed without risk sign-off'), ('B', 'Risk assessment done, supported and signed off'), ('C', 'Risk assessment done and supported, but not signed off'), ('D', 'Risk assessment raised concerns, not signed off'), ('E', 'No risk assessment performed yet'), ('F', 'Not sure if risk assessment is required')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Qtwentyone',
            field=models.CharField(choices=[('A', 'Yes, within the same process'), ('B', 'Yes, within different process but similar in functionality'), ('C', 'Yes, but totally different application'), ('D', 'No BOTs active for the area'), ('E', 'Not sure, need to investigate')], max_length=64, null=True),
        ),
    ]
