# Generated by Django 5.2 on 2025-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0006_answers_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='complete_by_time',
            field=models.CharField(choices=[('Do not wait', 'Do not wait'), ('No specific time', 'No specific time'), ('00:00:00', '00:00:00'), ('01:00:00', '01:00:00'), ('02:00:00', '02:00:00'), ('03:00:00', '03:00:00'), ('04:00:00', '04:00:00'), ('05:00:00', '05:00:00'), ('06:00:00', '06:00:00'), ('07:00:00', '07:00:00'), ('08:00:00', '08:00:00'), ('09:00:00', '09:00:00'), ('10:00:00', '10:00:00'), ('11:00:00', '11:00:00'), ('12:00:00', '12:00:00'), ('13:00:00', '13:00:00'), ('14:00:00', '14:00:00'), ('15:00:00', '15:00:00'), ('16:00:00', '16:00:00'), ('17:00:00', '17:00:00'), ('18:00:00', '18:00:00'), ('19:00:00', '19:00:00'), ('21:00:00', '21:00:00'), ('22:00:00', '22:00:00'), ('23:00:00', '23:00:00')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='complexity',
            field=models.CharField(choices=[('Mission critical', 'Mission critical'), ('Mandatory', 'Mandatory'), ('Very important', 'Very important'), ('Important', 'Important'), ('Less important', 'Less important'), ('Not important', 'Not important')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='criticality',
            field=models.CharField(choices=[('Mission critical', 'Mission critical'), ('Mandatory', 'Mandatory'), ('Very important', 'Very important'), ('Important', 'Important'), ('Less important', 'Less important'), ('Not important', 'Not important')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='customer_facing',
            field=models.CharField(choices=[('No - affects department', 'No - affects department'), ('No - affects business unit', 'No - affects business unit'), ('Internal stakeholders', 'Internal stakeholders'), ('Group internal stakeholders', 'Group internal stakeholders'), ('External stakeholders', 'External stakeholders'), ('Customer impacts', 'Customer impacts')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='day',
            field=models.CharField(choices=[('Month-end', 'Month-end'), ('Quarter-end', 'Quarter-end'), ('Year-end', 'Year-end'), ('Last day of month', 'Last day of month'), ('First day of year', 'First day of year'), ('Last day of year', 'Last day of year'), ('Specific date only', 'Specific date only'), ('Specific day only', 'Specific day only'), ('Specific week-day', 'Specific week-day'), ('Event driven', 'Event driven'), ('Ad hoc', 'Ad hoc')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='documentation',
            field=models.CharField(choices=[('Yes - detailed and current', 'Yes - detailed and current'), ('Yes - detailed but not current', 'Yes - detailed but not current'), ('Yes - not detailed', 'Yes - not detailed'), ('Yes - some gaps', 'Yes - some gaps'), ('Yes - very old', 'Yes - very old'), ('No', 'No'), ('Not sure - need to find out', 'Not sure - need to find out')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='errors',
            field=models.CharField(choices=[('No - none in past 3 months', 'No - none in past 3 months'), ('No - some in past 3 months', 'No - some in past 3 months'), ('Yes - human errors', 'Yes - human errors'), ('Yes - data incorrect', 'Yes - data incorrect'), ('Yes - exceptions noted', 'Yes - exceptions noted'), ('Yes - unexpected results', 'Yes - unexpected results'), ('Yes - process fails', 'Yes - process fails')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='event_type',
            field=models.CharField(choices=[('Activity', 'Activity'), ('Alert', 'Alert'), ('Exception', 'Exception'), ('Excess', 'Excess'), ('Procedure', 'Procedure'), ('Schedule', 'Schedule'), ('Update', 'Update')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='impact_if_failed',
            field=models.CharField(choices=[('Extreme', 'Extreme'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Low', 'Low'), ('Negligible', 'Negligible')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='impact_if_late',
            field=models.CharField(choices=[('Extreme', 'Extreme'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Low', 'Low'), ('Negligible', 'Negligible')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='impact_of_time_overun',
            field=models.CharField(choices=[('Extreme', 'Extreme'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Low', 'Low'), ('Negligible', 'Negligible')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='late_tolerance',
            field=models.CharField(choices=[('Zero tolerance', 'Zero tolerance'), ('Max 30min', 'Max 30min'), ('Max 1 hour', 'Max 1 hour'), ('Max 4 hours', 'Max 4 hours'), ('Max 1 day', 'Max 1 day'), ('Max 1 week', 'Max 1 week'), ('Max 1 month', 'Max 1 month'), ('More than 1 month', 'More than 1 month')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='manual_intervention',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Not Sure', 'Not Sure')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='optimised',
            field=models.CharField(choices=[('Yes - Recently', 'Yes - Recently'), ('Yes - Some time ago', 'Yes - Some time ago'), ('Busy re-engineering process now', 'Busy re-engineering process now'), ('No - considering it', 'No - considering it'), ('No - not necessary', 'No - not necessary'), ('No - not planned', 'No - not planned')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='recurrence',
            field=models.CharField(choices=[('Non-recurring', 'Non-recurring'), ('Recurring specific date', 'Recurring specific date'), ('Recurring daily', 'Recurring daily'), ('Recurring weekly', 'Recurring weekly'), ('Recurring monthly', 'Recurring monthly'), ('Recurring quarterly', 'Recurring quarterly'), ('Recurring annually', 'Recurring annually'), ('Recurring event', 'Recurring event')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='regulated',
            field=models.CharField(choices=[('No', 'No'), ('Yes - low impact', 'Yes - low impact'), ('Yes - Medium impact', 'Yes - Medium impact'), ('Yes - High impact', 'Yes - High impact'), ('Yes - Ultra high impact', 'Yes - Ultra high impact'), ('Yes - license threat', 'Yes - license threat')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='self_contained',
            field=models.CharField(choices=[('Yes - stand-alone', 'Yes - stand-alone'), ('Yes -  limited interaction', 'Yes -  limited interaction'), ('No - some dependencies', 'No - some dependencies'), ('No - many dependencies', 'No - many dependencies'), ('No - extensive and involved', 'No - extensive and involved')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='stable',
            field=models.CharField(choices=[('Stable for 6 months', 'Stable for 6 months'), ('Small changes within 6 months', 'Small changes within 6 months'), ('Many changes over past 6 months', 'Many changes over past 6 months'), ('Planned changes in next 90 days', 'Planned changes in next 90 days'), ('New process - less than 3 months', 'New process - less than 3 months'), ('Not sure - need to find out', 'Not sure - need to find out')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='time_dependencies',
            field=models.CharField(choices=[('No dependencies', 'No dependencies'), ('Wait for event / trigger', 'Wait for event / trigger'), ('After a certain time', 'After a certain time'), ('Before a certain time', 'Before a certain time'), ('Between specific times', 'Between specific times'), ('Anytime during business day', 'Anytime during business day'), ('Outside normal business hours', 'Outside normal business hours'), ('Overnight only', 'Overnight only')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='trigger',
            field=models.CharField(choices=[('Month-end', 'Month-end'), ('Quarter-end', 'Quarter-end'), ('Year-end', 'Year-end'), ('Last day of month', 'Last day of month'), ('First day of year', 'First day of year'), ('Last day of year', 'Last day of year'), ('Specific date only', 'Specific date only'), ('Specific day only', 'Specific day only'), ('Specific week-day', 'Specific week-day'), ('Event driven', 'Event driven'), ('Ad hoc', 'Ad hoc')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='understanding',
            field=models.CharField(choices=[('No idea', 'No idea'), ('Mostly', 'Mostly'), ('Somewhat', 'Somewhat'), ('Not really', 'Not really'), ('Not at all', 'Not at all')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='wait_until_time',
            field=models.CharField(choices=[('Do not wait', 'Do not wait'), ('No specific time', 'No specific time'), ('00:00:00', '00:00:00'), ('01:00:00', '01:00:00'), ('02:00:00', '02:00:00'), ('03:00:00', '03:00:00'), ('04:00:00', '04:00:00'), ('05:00:00', '05:00:00'), ('06:00:00', '06:00:00'), ('07:00:00', '07:00:00'), ('08:00:00', '08:00:00'), ('09:00:00', '09:00:00'), ('10:00:00', '10:00:00'), ('11:00:00', '11:00:00'), ('12:00:00', '12:00:00'), ('13:00:00', '13:00:00'), ('14:00:00', '14:00:00'), ('15:00:00', '15:00:00'), ('16:00:00', '16:00:00'), ('17:00:00', '17:00:00'), ('18:00:00', '18:00:00'), ('19:00:00', '19:00:00'), ('21:00:00', '21:00:00'), ('22:00:00', '22:00:00'), ('23:00:00', '23:00:00')], max_length=64, null=True),
        ),
    ]
